name: CI_action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
       node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
    
    - name: Build  
      run: npm run build

    - name: Install dependencies
      run: npm install
      working-directory: ./worksheet2/my-react-app

    - name: Build
      run: npm run build
      working-directory: ./worksheet2/my-react-app

    - name: Start
      run: npm start
      working-directory: ./worksheet2/my-react-app